eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  application:
    name: gamelogic-server
server:
  contextPath: /game/api
  port: 8080

itemServerName: http://item-server
playerServerName: http://player-server
matchServerName: http://match-server
