eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
ribbon:
  eager-load:
    enabled: true
    clients: item-server, player-server, match-server

spring:
  application:
    name: gamelogic-server
  rabbitmq:
    host: rabbitmq
server:
#  contextPath: /game/api
  port: 8080

itemServerName: http://item-server
playerServerName: http://player-server
matchServerName: http://match-server
