eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gamelogic-server

server:
#  contextPath: /game/api
  port: 8084

itemServerName: http://localhost:8083
playerServerName: http://localhost:8081
matchServerName: http://localhost:8082
