server:
  contextPath: /game/api
  port: 8084
itemServerName: http://localhost:8083
playerServerName: http://localhost:8081
matchServerName: http://localhost:8082
#gameApi:
#  player:
#    host: http://localhost
#    port: 8081
#    api: /game/api
#    path: ${gameApis.player.host}:${gameApis.player.port}${gameApis.player.api}
#  item:
#    host: http://localhost
#    port: 8083
#    api: /game/api
#    path: ${gameApis.item.host}:${gameApis.item.port}${gameApis.item.api}
#  match:
#    host: http://localhost
#    port: 8082
#    api: /game/api
#    path: ${gameApis.match.host}:${gameApis.match.port}${gameApis.match.api}
