version: '3.3'

services:

  postgres-user:
    image: "postgres:10"
  postgres-player:
    image: "postgres:10"
  postgres-item:
    image: "postgres:10"
  postgres-match:
    image: "postgres:10"

  redis:
    image: "redis:latest"
  rabbitmq:
    image: "rabbitmq:3"

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
#    ports:
#      - "8761:8761"

  player-server:
    build:
      context: ./player
      dockerfile: Dockerfile
    depends_on:
      - eureka
      - postgres-player
      - rabbitmq
      - redis
#      - item-server

#  player-server:
#    build:
#      context: ./player
#      dockerfile: Dockerfile
##    ports:
##      - "9001:8080"
#    depends_on:
#      - postgres-player
#      - eureka
#      - rabbitmq
#      - redis
#      - item-server

  match-server:
    build:
      context: ./match
      dockerfile: Dockerfile
#    ports:
#      - "9002:8080"
    depends_on:
      - eureka
      - postgres-match
      - rabbitmq

  item-server:
    build:
      context: ./item
      dockerfile: Dockerfile
#    ports:
#      - "9003:8080"
    depends_on:
      - postgres-item
      - eureka

  item-server-2:
    build:
      context: ./item
      dockerfile: Dockerfile
#    ports:
#      - "9003:8080"
    depends_on:
      - postgres-item
      - eureka

  gamelogic-server:
    build:
      context: ./gamelogic
      dockerfile: Dockerfile
#    ports:
#      - "9004:8080"
    depends_on:
      - eureka
      - rabbitmq
      - redis
      - player-server
      - match-server

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "10000:8080"
    depends_on:
      - redis
      - eureka
      - postgres-user
      - gamelogic-server
      - player-server
      - match-server
