version: '3.3'

services:
  postgres-user:
    image: "postgres:10"

  redis:
    image: "redis:latest"

  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "10000:8080"
    depends_on:
      - redis
