version: '3.3'

services:

  # "Redis is an open-source in-memory database project implementing a distributed,
  # in-memory key-value store with optional durability."
  # We use it here to store session tokens, in a way in which all services can
  # quickly access it for authentication purposes.
  # Think about it like a hash-map that you can access remotely.
  redis:
    image: "redis:latest"


  # Note: for simplicity I am not starting any real database in this example.
  # I am going to use embedded H2 databases.
  # However, ideally I should start here on Postgres per service that needs
  # a database (eg, zuul and user-service here)
#  eureka:
#    build:
#      context: ../eureka
#      dockerfile: Dockerfile
#    ports:
#      - "8761:8761"

  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "10000:8080"
    depends_on:
      - redis
#      - eureka


#  user-service:
#    build:
#      context: ./user-service
#      dockerfile: Dockerfile
#    ports:
#      - "10001:8080"
#    depends_on:
#      - redis


#  greetings:
#    build:
#      context: ./greetings
#      dockerfile: Dockerfile
#    ports:
#      - "10002:8080"
#    depends_on:
#      - redis