version: '3.3'

services:
  zuul:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - eureka
  eureka:
    build:
      context: ../eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  postgres-player:
    image: "postgres:10"

  player:
     build:
        context: ../player
        dockerfile: Dockerfile
     ports:
        - "9000:8080"
     depends_on:
        - postgres-player
        - eureka