version: '3.3'

services:

  postgres-user:
    image: "postgres:10"
  postgres-player:
    image: "postgres:10"
  postgres-item:
    image: "postgres:10"
  postgres-match:
    image: "postgres:10"

  redis:
    image: "redis:latest"

  rabbitmq:
    image: "rabbitmq:3"

  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "10000:8080"
    depends_on:
      - redis
      - eureka
      - postgres-user

  eureka:
    build:
      context: ../eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  player_0:
    build:
      context: ../player
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    depends_on:
      - postgres-player
      - eureka
      - rabbitmq

  match_0:
    build:
      context: ../match
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
    depends_on:
      - eureka
      - postgres-match
      - rabbitmq

  item_0:
    build:
      context: ../item
      dockerfile: Dockerfile
    ports:
      - "9003:8080"
    depends_on:
      - postgres-item
      - eureka

  gamelogic_0:
    build:
      context: ../gamelogic
      dockerfile: Dockerfile
    ports:
      - "9004:8080"
    depends_on:
      - eureka
      - rabbitmq
      - gateway
      - redis
      - item_0
      - player_0
      - match_0