version: '3.3'

services:

  eureka:
    build:
      context: ../eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  postgres-match:
    image: "postgres:10"
  rabbitmq:
    image: "rabbitmq:3"

  gamelogic_0:
     build:
        context: ./
        dockerfile: Dockerfile
     ports:
        - "9004:8080"
     depends_on:
        - eureka
        - rabbitmq

  match_0:
    build:
      context: ../match
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
    depends_on:
      - eureka
      - postgres-match
      - rabbitmq
