eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: item-server
server:
  contextPath: /game/api
  port: 8083