version: '3.3'

services:
  postgres:
    image: "postgres:10"

  service:
     build:
        context: ./
        dockerfile: Dockerfile
     ports:
        - "9000:8080"
     depends_on:
        - postgres