version: '3.3'

services:

  postgres-match:
    image: "postgres:10"

  eureka:
    build:
      context: ../eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  service:
     build:
        context: ./
        dockerfile: Dockerfile
     ports:
        - "9000:8080"
     depends_on:
        - postgres-match
        - eureka