
zuul:
  routes:
    player:
      path: /players/**
      sensitive-headers:
    item:
      path: /items/**
      sensitive-headers:
    match:
      path: /matches/**
      sensitive-headers:
    gamelogic:
      path: /play/**
      sensitive-headers:

spring:
  application:
    name: gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
server:
  port: 8080
  contextPath: /api/v1