
zuul:
  routes:
    player:
      path: /players/**
#      url: http://localhost/player-server/game/api/players

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/