
zuul:
  routes:
    player:
      path: /players/**
      sensitive-headers:
    item:
      path: /items/**
      sensitive-headers:
    match:
      path: /matches/**
      sensitive-headers:
    gamelogic:
      path: /play/**
      sensitive-headers:

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085
  contextPath: /api/v1