version: '3.3'

services:



  eureka:
    build:
      context: ../eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  postgres-player:
    image: "postgres:10"

  postgres-item:
    image: "postgres:10"

  rabbitmq:
    image: "rabbitmq:3"

  player_0:
     build:
        context: ./
        dockerfile: Dockerfile
     ports:
        - "9000:8080"
     depends_on:
        - postgres-player
        - eureka
        - rabbitmq

  item_0:
    build:
      context: ../item
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
    depends_on:
      - postgres-item
      - eureka

  item_1:
    build:
      context: ../item
      dockerfile: Dockerfile
    ports:
      - "9002:8080"
    depends_on:
      - postgres-item
      - eureka
      - item_0